root = "."
tmp_dir = "tmp"

[build]
cmd = "cmd /c \"go build -o .\\tmp\\prismd.exe .\\cmd\\prismd && .\\tmp\\prismd.exe --port 5666 --data .\\data\""
bin = ""

[log]
time = true

[misc]
clean_on_exit = true